### ISSUE TITLE
Remove the title from the org icon

### ISSUE THREAD

**Issue by bloxxite** [ionlang/ionlang#1]
It looks ugly with the title in the icon.

**Comment by cloudrex** [comment]
I appreciate the suggestion but I think it's more recognizable this way instead of just the logo would look out of context.

**Comment by bloxxite** [comment]
No, not out of context look at all these orgs without title.

https://github.com/reactjs
https://github.com/angular
https://github.com/dependabot
https://github.com/ruby
https://github.com/nodejs
https://github.com/denoland
https://github.com/google
https://github.com/oracle
https://github.com/microsoft
https://github.com/github
https://github.com/lua
https://github.com/DiscordMix

It doesn't look out of context! Maybe because you made the logo too small?
